Constrain version of lark to < 1.3.1
In Lark version 1.3.1, `common.py` introduced a runtime `TypeError`:

1. Line 21 defines `_LexerArgType` as a string forward reference:

   ```python
   _LexerArgType: 'TypeAlias' = 'Union[Literal[...], Type[Lexer]]'
   ```

2. Line 37 inside class `LexerConf` evaluates `lexer_type: _LexerArgType | None`

3. Because the module does not use from `__future__ import annotations`,
   Python evaluates `'Union[...]' | None` at module import time, raising
   an exception:

   ```python
   TypeError: unsupported operand type(s) for |: 'str' and 'NoneType'
   ```

4. During pytest test collection, lark is imported by rfc3987_syntax,
   which is imported by jsonschema, which is imported by nbformat, and
   this import would fail with the error above.